/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 nla_ostrich--01_1k.glb --transform 
Files: nla_ostrich--01_1k.glb [2.72MB] > /home/pjos/code/projects/nostrbama/01/nostrbama/public/nla_ostrich--01_1k-transformed.glb [530.02KB] (81%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function Character({ animation, ...props }) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/game/nla_ostrich--01_1k-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.25).play();
    return () => actions?.[animation]?.fadeOut(0.25);
  }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.RootBone} />
          <skinnedMesh
            name="Ostrich"
            geometry={nodes.Ostrich.geometry}
            material={materials.Material}
            skeleton={nodes.Ostrich.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/game/nla_ostrich--01_1k-transformed.glb");
